Public Class DfieldDef
    Public Enum eTipoComprobante
        IdTipoComprobante = 0
        Descripcion = 1
    End Enum
    Public Enum eTasaIVA
        Id_Tasa_IVA = 0
        Descripcion = 1
        Tasa = 2
    End Enum
    Public Enum eRubros
        Id_Rubro = 0
        Descripcion = 1
    End Enum
    Public Enum eNumeroComprobante
        Id_Comprobante = 0
        Descripcion = 1
        Numeracion = 2
        Id_Empresa = 3
        Id_Tipo_Comprobante = 4
    End Enum
    Public Enum eEmpresa
        Id_Empresa = 0
        Razon_Social = 1
        Calle = 2
        Piso = 3
        Nro = 4
        Localidad = 5
        Codigo_Postal = 6
        CUIT = 7
        Ingresos_Brutos = 8
        Id_Responsabilidad_IVA = 9
        Responsabilidad_IVA = 10
        Nro_Sucursal = 11
        Provincia = 12
    End Enum
    Public Enum eArticulos
        Id_Producto = 0
        Id_Rubro = 1
        Codigo_Barras = 2
        Descripcion = 3
        Id_Proveedor = 4
        Id_Tasa_IVA = 5
        Stock_Minimo = 6
        Stock = 7
        Pesable = 8
        Tipo_Unidad = 9
        Cantidad_Unid_Caja = 10
        Peso_Unidad = 11
        INHABILITAR = 12
        Cod_Prod_Proveedor = 13
    End Enum
    Public Enum eListaPrecio
        Id_Lista_Precio = 0
        Descripcion = 1
    End Enum
    Public Enum eListaPrecioArticulo
        Id_Lista_Precio = 0
        Id_Producto = 1
        Descripcion = 2
        Precio_Costo = 3
        Rentabilidad = 4
        Precio_Venta = 5
        Precio_Kilo = 6
    End Enum
    Public Enum eProveedor
        Id_Proveedor = 0
        Razon_Social = 1
        Calle = 2
        Piso = 3
        Nro = 4
        Localidad = 5
        Codigo_Postal = 6
        Provincia = 7
        Telefono = 8
        Celular = 9
        CUIT = 10
        E_Mail = 11
        Responsabilidad_IVA = 12
        Saldo_CC = 13
    End Enum
    Public Enum eArticuloCuerpoDocumento
        Id_Producto = 0
        Id_Rubro = 1
        Codigo_Barras = 2
        Descripcion = 3
        Id_Proveedor = 4
        Id_Tasa_IVA = 5
        Tasa_IVA = 6
        Stock_Minimo = 7
        Stock = 8
        Pesable = 9
        Tipo_Unidad = 10
        Cantidad_Unid_Caja = 11
        Peso_Unidad = 12
        INHABILITAR = 13
        Cod_Prod_Proveedor = 14
        Id_Lista_Precio = 15
        Producto_Lista_Precio = 16
        DescripcionListaPrecio = 17
        Precio_Costo = 18
        Rentabilidad = 19
        Precio_Venta = 20
        Precio_Kilo = 21
        Cantidad = 22
        Importe = 23
    End Enum
    Public Enum eConfiguracion
        Id_Configuracion = 0
        Puerto_Comm = 1
        Nro_Puerto = 2
        Nombre_Balanza = 3
        Lector_Codigo_Barras = 4
        Id_Lista_Precio = 5
        Lista_Precio = 6
        Id_Tasa_IVA = 7
        NroEquipo = 8
    End Enum
    Public Enum eConfiguracionComprobantes
        Id_Comprobante = 0
        Descripcion = 1
        CantidadCopias = 2
        Impresora = 3
    End Enum
    Public Enum eCliente
        Id_Cliente = 0
        Nombre = 1
        Apellido = 2
        Calle = 3
        Piso = 4
        Nro = 5
        Saldo_CC = 6
        CUIT = 7
        Provincia = 8
        Telefono = 9
        Celular = 10
        E_Mail = 11
        Codigo_Postal = 12
        Responsabilidad_IVA = 13
        Localidad = 14
        INHABILITAR = 15
    End Enum
    Public Enum eEncabezadoFactura
        Punto_Venta = 0
        Tipo_Comprobante = 1
        Numero_Comprobante = 2
        Comprobante = 3
        Numero_Cliente = 4
        Nombre = 5
        Apellido = 6
        Situacion_Frente_A_IVA = 7
        ID_Forma_Pago = 8
        Forma_Pago = 9
        Fecha_Comprobante = 10
        Codigo_Vendedor = 11
        Neto_Grabado_21 = 12
        Neto_Grabado_105 = 13
        Neto_Grabado_27 = 14
        Sub_Total = 15
        Conc_No_Grabado = 16
        Exentos = 17
        IVA_Facturado21 = 18
        IVA_Facturado105 = 19
        IVA_Facturado27 = 20
        IVA_Resp_No_Inscripto = 21
        Persepciones = 22
        PorcDescuentos = 23
        Descuentos = 24
        Retenciones = 25
        Total = 26
        Cancelado = 27
        Signo = 28
    End Enum
    Public Enum eCuerpoFactura
        IdCuerpoFactura = 0
        Punto_Venta = 1
        Tipo_Comprobante = 2
        Numero_Comprobante = 3
        Comprobante = 4
        Numero_Articulo = 5
        Descripcion = 6
        Cantidad = 7
        Precio_Unitario = 8
        Signo = 9
    End Enum
    Public Enum eEncabezadoFacturaProveedor
        Id_Proveedor = 0
        Punto_Venta = 1
        Tipo_Comprobante = 2
        Numero_Comprobante = 3
        Comprobante = 4
        Razon_Social = 5
        Situacion_Frente_A_IVA = 6
        Forma_Pago = 7
        Fecha_Comprobante = 8
        Codigo_Vendedor = 9
        Neto_Grabado = 10
        Conc_No_Grabado = 11
        Exentos = 12
        IVA_Facturado = 13
        IVA_Resp_No_Inscripto = 14
        Persepciones = 15
        Descuentos = 16
        Retenciones = 17
        Total = 18
        Cancelado = 19
    End Enum
    Public Enum eCuerpoFacturaProveedor
        IdCuerpoFactura = 0
        Punto_Venta = 1
        Tipo_Comprobante = 2
        Numero_Comprobante = 3
        Comprobante = 4
        Numero_Articulo = 5
        Descripcion = 6
        Cantidad = 7
        Precio_Unitario = 8
    End Enum
    Public Enum eConstantes
        FACTURA = 0
        NotaCredito = 1
        NotaDebito = 2
        Remito = 3
        VentasRapidas = 4
        ArticulosFacturacion = 5
        Si = 6
        Contado = 7
        CuentaCorriente = 8
        Encabezado_Factura = 9
        Numeracion_Comprobante = 10
        Cuerpo_Factura = 11
        Producto = 12
        Imputaciones = 13
        IngresoEfectivo = 14
        IngresoNotaDebito = 15
        EgresoNotaCredito = 16
        IngresoCuentaCorriente = 17
        IngresoNotaDebitoCuentaCorriente = 18
        EgresoNotaCreditoCuentaCorriente = 19
        cliente = 20
        Agregar_Cliente = 21
        Nombre = 22
        Apellido = 23
        Calle = 24
        CUIT = 25
        Provincia = 26
        Telefono = 27
        Celular = 28
        E_Mail = 29
        Codigo_Postal = 30
        Responsabilidad_IVA = 31
        Localidad = 32
        Modificar_Cliente = 33
        Empresa = 34
        Condicion_Frente_Al_IVA = 35
        Configuracion = 36
        Lista_Precio = 37
        Producto_Lista_Precio = 38
        ArticulosVentaRapida = 39
        ArticulosNotaCredito = 40
        ArticulosNotaDebito = 41
        Agregar_Producto = 42
        Modificar_Articulo = 43
        Id_Producto = 44
        Id_Rubro = 45
        Codigo_Barras = 46
        Descripcion = 47
        Pesable = 48
        Tipo_Unidad = 49
        Agregar_Lista_Precio = 50
        Tasa_IVA = 51
        Modificar_Lista_Precio = 52
        No = 53
        rubro = 54
        Proveedor = 55
        Registrar = 56
        Actualizar = 57
        Razon_Social = 58
        Piso = 59
        Agregar_Empresa = 60
        Modificar_Empresa = 61
        Agregar_NumeroComprobante = 62
        Numeracion = 63
        Modificar_NumeroComprobante = 64
        Agregar_Proveedor = 65
        Modificar_Proveedor = 66
        Punto_Venta = 67
        Tipo_Comprobante = 68
        Numero_Comprobante = 69
        Comprobante = 70
        CancelacionNotaCredito = 71
        EmpresaArticulo = 72
        AgregarArticuloEmpresa = 73
        Tipos_Comprobantes = 74
        ConfiguracionComprobantes = 75
        FACTURAPROVEEDOR = 76
        NotaCreditoProveedor = 77
        NotaDebitoProveedor = 78
        Encabezado_Factura_Proveedor = 79
        Cuerpo_Factura_Proveedor = 80
        Imputaciones_Proveedor = 81
        CuentaCorriente_Proveedor = 82
        Nota_De_Credito = 83
        Nota_De_Debito = 84
        Venta_Rapida = 85
        Cod_Producto = 86
        Cod_Rubro = 87
        Cod_Barras = 88
        EntradaSalidaMercaderias = 89
        Encabezado_Entrada_Salida_Mercaderia = 90
        Cuerpo_Entrada_Salida_Mercaderia = 91
        EntradaMercaderia = 92
        SalidaMercaderia = 93
        Eliminar_Empresa = 94
        Recibo = 95
        BuscarComprobante = 96
        Nota_De_Credito_Int = 97
        Caja = 98
        Ingresos = 99
        Egresos = 100
        IngresosEgresos = 101
    End Enum

    Public Enum eCondicionFrenteAlIVa
        Id_Condicion_IVA = 0
        Descripcion = 1
    End Enum
End Class
